"""Add optional colour field.

Revision ID: 264a1166d32d
Revises: 7d90c5004964
Create Date: 2018-03-14 14:08:59.458619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264a1166d32d'
down_revision = '7d90c5004964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('colour', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'colour')
    # ### end Alembic commands ###
