"""Initial migration.

Revision ID: 6fb6ef0531a6
Revises: 
Create Date: 2018-03-13 11:33:38.623440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fb6ef0531a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('long', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_expires'), 'note', ['expires'], unique=False)
    op.create_index('note_lat_long_index', 'note', ['lat', 'long'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('note_lat_long_index', table_name='note')
    op.drop_index(op.f('ix_note_expires'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
