"""Add altitude support.

Revision ID: 7d90c5004964
Revises: 6fb6ef0531a6
Create Date: 2018-03-13 12:46:02.517219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d90c5004964'
down_revision = '6fb6ef0531a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('altitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'altitude')
    # ### end Alembic commands ###
